name: Create File

on:
  workflow_dispatch:  # Solo ejecución manual

jobs:
  create-file:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Crear un nuevo archivo con contenido
        run: |
          echo "Este es un archivo generado automáticamente por GitHub Actions." > archivo_autogenerado.txt
          
      - name: Hacer commit del nuevo archivo
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add archivo_autogenerado.txt
          git commit -m "Agregar archivo generado automáticamente"
          
      - name: Push to the repository
        run: |
          git remote set-url origin https://github.com/${{ github.repository }}.git
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
