name: Auto Comment

on:
  workflow_dispatch:  # Solo permite ejecución manual

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Crear un comentario en el issue
        run: |
          gh auth login --with-token <<< ${{ secrets.GITHUB_TOKEN }}
          gh issue comment 1 --body "¡Este es un comentario automático generado por GitHub Actions! 😊 Este comentario se publica cuando se ejecuta manualmente."
