name: Daily Log at 9:00 AM UTC

on:
#  schedule:
  #  - cron: '0 9 * * *'   9:00 AM UTC todos los días
  workflow_dispatch:  # Permite ejecutar el workflow manualmente desde GitHub

jobs:
  log-time:
    runs-on: ubuntu-latest  # Usamos una máquina virtual con Ubuntu

    steps:
    - name: Log time
      run: |
        # Imprime la hora actual en el log
        echo "The current UTC time is: $(date --utc)"
